
analysis:
  markers:
    # Left side
    - "LHipAngles"
    - "LKneeAngles"
    - "LAnkleAngles"
    - "LPelvisAngles"
    - "LThoraxAngles"
    - "LSpineAngles"
    - "LFootProgressAngles"
    # Right side
    - "RHipAngles"
    - "RKneeAngles"
    - "RAnkleAngles"
    - "RPelvisAngles"
    - "RThoraxAngles"
    - "RSpineAngles"
    - "RFootProgressAngles"
    
mapping:
  markers:
    # Foot
    l_heel: "LHEE"
    r_heel: "RHEE"
    l_toe: "LTOE"
    r_toe: "RTOE"
    

    # Hip
    l_ant_hip: "LASI"
    r_ant_hip: "RASI"
    l_post_hip: "LPSI"
    r_post_hip: "RPSI"
    sacrum: "SACR"
    
  
  




